name: flutter_monorepo

packages:
  - apps/**
  - packages/**

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # # Only allow versioning to happen on main branch.
    branch: main
    # Additionally build a changelog at the root of the workspace.
    releaseUrl: true

scripts:
  lint:all:
    run: melos run analyze-ci && melos run format-ci
    description: Run all static analysis checks.

  format:
    run: melos exec dart format . --fix
    description: Run `dart format` in all packages.

  # analyze:
  #   run: melos exec -- flutter analyze .
  #   description: Run `dart analyze` in all packages.

  # test:selective_unit_test:
  #   run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
  #   description: Run Flutter tests for a specific package in this project.
  #   select-package:
  #     flutter: true
  #     dir-exists: test

  # test:
  #   run: melos run test:selective_unit_test --no-select
  #   description: Run all Flutter tests in this project.

  # gen_coverage: melos exec -- "\$MELOS_ROOT_PATH/combine_coverage.sh"
